/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 10 12:37:52 GMT 2026
 */

package org.apache.bookkeeper.bookie.storage.ldb;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.ByteBufAllocator;
import io.netty.buffer.CompositeByteBuf;
import io.netty.buffer.EmptyByteBuf;
import io.netty.buffer.PooledByteBufAllocator;
import io.netty.buffer.UnpooledByteBufAllocator;
import io.netty.buffer.UnpooledUnsafeHeapByteBuf;
import org.apache.bookkeeper.bookie.storage.ldb.WriteCache;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class WriteCache_ESTest extends WriteCache_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache(pooledByteBufAllocator0, 1966L, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int int0 = WriteCache.align64(2240);
      assertEquals(2240, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int int0 = WriteCache.align64((-3610));
      assertEquals((-3584), int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      WriteCache writeCache0 = new WriteCache((ByteBufAllocator) null, 0L);
      // Undeclared exception!
      try { 
        writeCache0.put(0L, 0L, (ByteBuf) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.storage.ldb.WriteCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(pooledByteBufAllocator0);
      // Undeclared exception!
      try { 
        writeCache0.put((-1L), 0L, emptyByteBuf0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Keys and values must be >= 0
         //
         verifyException("org.apache.bookkeeper.util.collections.ConcurrentLongLongHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      WriteCache writeCache0 = new WriteCache((ByteBufAllocator) null, 0L);
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      CompositeByteBuf compositeByteBuf0 = unpooledByteBufAllocator0.compositeHeapBuffer();
      writeCache0.put(0L, 0L, compositeByteBuf0);
      // Undeclared exception!
      try { 
        writeCache0.getLastEntry(0L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.storage.ldb.WriteCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, (-9223372036854775808L));
      // Undeclared exception!
      try { 
        writeCache0.getLastEntry((-9223372036854775808L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Keys and values must be >= 0
         //
         verifyException("org.apache.bookkeeper.util.collections.ConcurrentLongLongHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, (-9223372036854775808L));
      // Undeclared exception!
      try { 
        writeCache0.get((-9223372036854775808L), (-9223372036854775808L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Keys and values must be >= 0
         //
         verifyException("org.apache.bookkeeper.util.collections.ConcurrentLongLongPairHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache(pooledByteBufAllocator0, (-899L), 4);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.storage.ldb.WriteCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache(pooledByteBufAllocator0, (-1L), 1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.apache.bookkeeper.bookie.storage.ldb.WriteCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 1, 1);
      assertTrue(writeCache0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache(pooledByteBufAllocator0, 2862933555777941757L);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.storage.ldb.WriteCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache(pooledByteBufAllocator0, (-4096L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // initialCapacity : -4096 (expected: >= 0)
         //
         verifyException("io.netty.util.internal.ObjectUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = new UnpooledByteBufAllocator(false, false, false);
      WriteCache writeCache0 = new WriteCache(unpooledByteBufAllocator0, 0L);
      ByteBuf byteBuf0 = writeCache0.get(838, 3315L);
      assertNull(byteBuf0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator(false);
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      writeCache0.close();
      assertTrue(writeCache0.isEmpty());
  }

// It fails on github because too much memory
//  @Test(timeout = 4000)
//  public void test15()  throws Throwable  {
//      WriteCache writeCache0 = new WriteCache((ByteBufAllocator) null, 4294967296L);
//  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator(false);
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      long long0 = writeCache0.size();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator(false);
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      writeCache0.clear();
      assertEquals(0L, writeCache0.size());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      boolean boolean0 = writeCache0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(pooledByteBufAllocator0);
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L, 1);
      writeCache0.deleteLedger(0L);
      writeCache0.put(0L, 0L, emptyByteBuf0);
      WriteCache.EntryConsumer writeCache_EntryConsumer0 = mock(WriteCache.EntryConsumer.class, new ViolatedAssumptionAnswer());
      writeCache0.forEach(writeCache_EntryConsumer0);
      assertEquals(0L, writeCache0.size());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(pooledByteBufAllocator0);
      writeCache0.put(0L, 0L, emptyByteBuf0);
      // Undeclared exception!
      try { 
        writeCache0.forEach((WriteCache.EntryConsumer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.storage.ldb.WriteCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(pooledByteBufAllocator0);
      WriteCache.EntryConsumer writeCache_EntryConsumer0 = mock(WriteCache.EntryConsumer.class, new ViolatedAssumptionAnswer());
      writeCache0.forEach(writeCache_EntryConsumer0);
      writeCache0.put(0L, 0L, emptyByteBuf0);
      // Undeclared exception!
      writeCache0.forEach((WriteCache.EntryConsumer) null);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      WriteCache.EntryConsumer writeCache_EntryConsumer0 = mock(WriteCache.EntryConsumer.class, new ViolatedAssumptionAnswer());
      writeCache0.forEach(writeCache_EntryConsumer0);
      // Undeclared exception!
      writeCache0.forEach((WriteCache.EntryConsumer) null);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      writeCache0.getLastEntry(796L);
      assertEquals(0L, writeCache0.size());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(pooledByteBufAllocator0);
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      writeCache0.put(0L, 0L, emptyByteBuf0);
      boolean boolean0 = writeCache0.hasEntry(0L, 0L);
      assertTrue(boolean0);
      assertTrue(writeCache0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      boolean boolean0 = writeCache0.hasEntry(0L, 0);
      assertTrue(writeCache0.isEmpty());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(pooledByteBufAllocator0);
      WriteCache writeCache0 = new WriteCache((ByteBufAllocator) null, 0L, 1);
      writeCache0.put(16L, 1, emptyByteBuf0);
      // Undeclared exception!
      try { 
        writeCache0.get(16L, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.storage.ldb.WriteCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(pooledByteBufAllocator0);
      boolean boolean0 = writeCache0.put(0L, (-2L), emptyByteBuf0);
      assertTrue(boolean0);
      assertTrue(writeCache0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      UnpooledUnsafeHeapByteBuf unpooledUnsafeHeapByteBuf0 = new UnpooledUnsafeHeapByteBuf(pooledByteBufAllocator0, 565, 565);
      ByteBuf byteBuf0 = unpooledUnsafeHeapByteBuf0.writeShortLE(565);
      boolean boolean0 = writeCache0.put(0L, 0L, byteBuf0);
      assertFalse(boolean0);
      assertEquals(0L, writeCache0.size());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache((ByteBufAllocator) null, 1172, 1172);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Max segment size needs to be in form of 2^n
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache((ByteBufAllocator) null, (-3602), (-3602));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      WriteCache writeCache0 = new WriteCache((ByteBufAllocator) null, 0L);
      writeCache0.count();
      assertTrue(writeCache0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(pooledByteBufAllocator0);
      writeCache0.put(0L, 0L, emptyByteBuf0);
      ByteBuf byteBuf0 = writeCache0.getLastEntry(0L);
      assertTrue(writeCache0.isEmpty());
      assertNotNull(byteBuf0);
  }
}
