/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 07 16:57:08 GMT 2026
 */

package org.apache.bookkeeper.bookie.storage.ldb;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.ByteBufAllocator;
import io.netty.buffer.PooledByteBufAllocator;
import io.netty.buffer.UnpooledByteBufAllocator;
import io.netty.buffer.UnpooledUnsafeHeapByteBuf;
import org.apache.bookkeeper.bookie.storage.ldb.WriteCache;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class WriteCache_ESTest extends WriteCache_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      UnpooledUnsafeHeapByteBuf unpooledUnsafeHeapByteBuf0 = new UnpooledUnsafeHeapByteBuf(pooledByteBufAllocator0, 35, 200);
      boolean boolean0 = writeCache0.put(1396L, 2533L, unpooledUnsafeHeapByteBuf0);
      assertTrue(boolean0);
      assertTrue(writeCache0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      UnpooledUnsafeHeapByteBuf unpooledUnsafeHeapByteBuf0 = new UnpooledUnsafeHeapByteBuf(pooledByteBufAllocator0, 64, 1824);
      ByteBuf byteBuf0 = unpooledUnsafeHeapByteBuf0.writeByte(1824);
      boolean boolean0 = writeCache0.put(2048L, 0L, byteBuf0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache((ByteBufAllocator) null, 0L, (-3601));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator(false);
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0, 4);
      assertEquals(0L, writeCache0.size());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int int0 = WriteCache.align64(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int int0 = WriteCache.align64(54);
      assertEquals(64, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int int0 = WriteCache.align64((-1440));
      assertEquals((-1408), int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      // Undeclared exception!
      try { 
        writeCache0.put(0L, 0L, (ByteBuf) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.storage.ldb.WriteCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(unpooledByteBufAllocator0, 0);
      ByteBuf byteBuf0 = unpooledByteBufAllocator0.directBuffer(0, 0);
      // Undeclared exception!
      try { 
        writeCache0.put((-1710L), 0, byteBuf0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Keys and values must be >= 0
         //
         verifyException("org.apache.bookkeeper.util.collections.ConcurrentLongLongHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(unpooledByteBufAllocator0, (-9223372036854775808L));
      // Undeclared exception!
      try { 
        writeCache0.hasEntry((-9223372036854775808L), (-9223372036854775808L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Keys and values must be >= 0
         //
         verifyException("org.apache.bookkeeper.util.collections.ConcurrentLongLongPairHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache((ByteBufAllocator) null, 0);
      ByteBuf byteBuf0 = unpooledByteBufAllocator0.directBuffer(0, 0);
      writeCache0.put(0, 0, byteBuf0);
      // Undeclared exception!
      try { 
        writeCache0.getLastEntry(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.storage.ldb.WriteCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(unpooledByteBufAllocator0, (-9223372036854775808L));
      // Undeclared exception!
      try { 
        writeCache0.getLastEntry((-9223372036854775808L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Keys and values must be >= 0
         //
         verifyException("org.apache.bookkeeper.util.collections.ConcurrentLongLongHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      // Undeclared exception!
      try { 
        writeCache0.get((-2083L), (-2083L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Keys and values must be >= 0
         //
         verifyException("org.apache.bookkeeper.util.collections.ConcurrentLongLongPairHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0);
      // Undeclared exception!
      try { 
        writeCache0.deleteLedger((-1257L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Keys and values must be >= 0
         //
         verifyException("org.apache.bookkeeper.util.collections.ConcurrentLongHashSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache(unpooledByteBufAllocator0, (-2091L), 4);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.storage.ldb.WriteCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache(unpooledByteBufAllocator0, (-1L), 1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.apache.bookkeeper.bookie.storage.ldb.WriteCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache(unpooledByteBufAllocator0, (-2147483648L));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.storage.ldb.WriteCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache(pooledByteBufAllocator0, (-2149L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // initialCapacity : -2149 (expected: >= 0)
         //
         verifyException("io.netty.util.internal.ObjectUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(unpooledByteBufAllocator0, 2147482623L);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(unpooledByteBufAllocator0, 0);
      ByteBuf byteBuf0 = unpooledByteBufAllocator0.directBuffer(0, 0);
      writeCache0.put(0, 0, byteBuf0);
      boolean boolean0 = writeCache0.hasEntry(0, 0);
      assertTrue(boolean0);
      assertEquals(0L, writeCache0.size());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache((ByteBufAllocator) null, 0);
      ByteBuf byteBuf0 = unpooledByteBufAllocator0.directBuffer(0, 0);
      writeCache0.put(0, 0, byteBuf0);
      // Undeclared exception!
      try { 
        writeCache0.get(0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.storage.ldb.WriteCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      writeCache0.get(9L, 0L);
      assertEquals(0L, writeCache0.size());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(unpooledByteBufAllocator0, 0);
      ByteBuf byteBuf0 = unpooledByteBufAllocator0.directBuffer(0, 0);
      boolean boolean0 = writeCache0.put(0, (-889L), byteBuf0);
      assertTrue(boolean0);
      assertTrue(writeCache0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      writeCache0.close();
      assertTrue(writeCache0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      writeCache0.count();
      assertEquals(0L, writeCache0.size());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      boolean boolean0 = writeCache0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(unpooledByteBufAllocator0, 0);
      ByteBuf byteBuf0 = unpooledByteBufAllocator0.directBuffer(0, 0);
      writeCache0.deleteLedger(0);
      boolean boolean0 = writeCache0.put(0, 0, byteBuf0);
      assertTrue(boolean0);
      
      writeCache0.forEach((WriteCache.EntryConsumer) null);
      assertTrue(writeCache0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(unpooledByteBufAllocator0, 0);
      ByteBuf byteBuf0 = unpooledByteBufAllocator0.directBuffer(0, 0);
      WriteCache.EntryConsumer writeCache_EntryConsumer0 = mock(WriteCache.EntryConsumer.class, new ViolatedAssumptionAnswer());
      writeCache0.forEach(writeCache_EntryConsumer0);
      writeCache0.put(0, 0, byteBuf0);
      // Undeclared exception!
      writeCache0.forEach((WriteCache.EntryConsumer) null);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(unpooledByteBufAllocator0, 0);
      WriteCache.EntryConsumer writeCache_EntryConsumer0 = mock(WriteCache.EntryConsumer.class, new ViolatedAssumptionAnswer());
      writeCache0.forEach(writeCache_EntryConsumer0);
      // Undeclared exception!
      writeCache0.forEach((WriteCache.EntryConsumer) null);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      writeCache0.getLastEntry(2529L);
      assertEquals(0L, writeCache0.size());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      boolean boolean0 = writeCache0.hasEntry(9L, 2862933555777941757L);
      assertFalse(boolean0);
      assertTrue(writeCache0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(unpooledByteBufAllocator0, 1073L, 4);
      assertTrue(writeCache0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache(pooledByteBufAllocator0, 1381L, 966);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Max segment size needs to be in form of 2^n
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = null;
      try {
        writeCache0 = new WriteCache(unpooledByteBufAllocator0, 0, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      long long0 = writeCache0.size();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(unpooledByteBufAllocator0, 0);
      ByteBuf byteBuf0 = unpooledByteBufAllocator0.directBuffer(0, 0);
      writeCache0.put(0, 0, byteBuf0);
      ByteBuf byteBuf1 = writeCache0.getLastEntry(0);
      assertNotNull(byteBuf1);
      assertEquals(0L, writeCache0.size());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      WriteCache writeCache0 = new WriteCache(pooledByteBufAllocator0, 0L);
      writeCache0.clear();
      assertEquals(0L, writeCache0.size());
  }
}
