/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 10 12:36:31 GMT 2026
 */

package org.apache.bookkeeper.bookie;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.ByteBufAllocator;
import io.netty.buffer.CompositeByteBuf;
import io.netty.buffer.PooledByteBufAllocator;
import io.netty.buffer.UnpooledByteBufAllocator;
import io.netty.buffer.UnpooledHeapByteBuf;
import java.io.FileDescriptor;
import java.io.IOException;
import java.nio.channels.ClosedChannelException;
import java.nio.channels.FileChannel;
import java.nio.channels.NonWritableChannelException;
import org.apache.bookkeeper.bookie.BufferedChannel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFileInputStream;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class BufferedChannel_ESTest extends BufferedChannel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1568);
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = new UnpooledByteBufAllocator(false);
      CompositeByteBuf compositeByteBuf0 = unpooledByteBufAllocator0.compositeBuffer();
      CompositeByteBuf compositeByteBuf1 = compositeByteBuf0.writeFloat(0.0F);
      // Undeclared exception!
      try { 
        bufferedChannel0.read((ByteBuf) compositeByteBuf1, 1034L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // minWritableBytes : -1034 (expected: >= 0)
         //
         verifyException("io.netty.util.internal.ObjectUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      UnpooledHeapByteBuf unpooledHeapByteBuf0 = new UnpooledHeapByteBuf(pooledByteBufAllocator0, 1, 1);
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1, 42L);
      // Undeclared exception!
      try { 
        bufferedChannel0.read((ByteBuf) unpooledHeapByteBuf0, 42L, 15);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // dest buffer remaining capacity is not enough(must be at least as \"length\"=15)
         //
         verifyException("org.apache.bookkeeper.bookie.BufferedChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, true, 24);
      CompositeByteBuf compositeByteBuf1 = compositeByteBuf0.writeByte(24);
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 24, 604800L);
      bufferedChannel0.write(compositeByteBuf1);
      bufferedChannel0.write(compositeByteBuf1);
      assertEquals(2L, bufferedChannel0.position());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      FileChannel fileChannel0 = mockFileInputStream0.getChannel();
      mockFileInputStream0.skip(25L);
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel((ByteBufAllocator) null, fileChannel0, 0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.BufferedChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = new UnpooledByteBufAllocator(true);
      BufferedChannel bufferedChannel0 = new BufferedChannel(unpooledByteBufAllocator0, fileChannel0, 1568, 0);
      bufferedChannel0.flushAndForceWrite(true);
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = new UnpooledByteBufAllocator(true);
      BufferedChannel bufferedChannel0 = new BufferedChannel(unpooledByteBufAllocator0, fileChannel0, 0, 1568, 301L);
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1568);
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = new UnpooledByteBufAllocator(true);
      CompositeByteBuf compositeByteBuf0 = unpooledByteBufAllocator0.compositeBuffer();
      int int0 = bufferedChannel0.read((ByteBuf) compositeByteBuf0, (long) 0, (-2147012914));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, false, 18);
      compositeByteBuf0.writeByte(18);
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 18, 18);
      bufferedChannel0.write(compositeByteBuf0);
      long long0 = bufferedChannel0.getUnpersistedBytes();
      assertEquals(1L, bufferedChannel0.position());
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, true, 24);
      CompositeByteBuf compositeByteBuf1 = compositeByteBuf0.writeByte(24);
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 24, 604800L);
      bufferedChannel0.write(compositeByteBuf1);
      int int0 = bufferedChannel0.getNumOfBytesInWriteBuffer();
      assertEquals(1L, bufferedChannel0.position());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, true, 24);
      CompositeByteBuf compositeByteBuf1 = compositeByteBuf0.writeByte(24);
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 24, 604800L);
      bufferedChannel0.write(compositeByteBuf1);
      bufferedChannel0.flushAndForceWriteIfRegularFlush(true);
      long long0 = bufferedChannel0.getFileChannelPosition();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, false, 1);
      compositeByteBuf0.writeByte((-6239));
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 753, 1172L);
      bufferedChannel0.close();
      // Undeclared exception!
      try { 
        bufferedChannel0.write(compositeByteBuf0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // refCnt: 0
         //
         verifyException("io.netty.buffer.AbstractByteBuf", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, true, 24);
      compositeByteBuf0.writeByte(0);
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 0, 0L);
      // Undeclared exception!
      bufferedChannel0.write(compositeByteBuf0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1, 42L);
      bufferedChannel0.close();
      // Undeclared exception!
      try { 
        bufferedChannel0.flushAndForceWriteIfRegularFlush(false);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // refCnt: 0
         //
         verifyException("io.netty.buffer.AbstractByteBuf", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1, 60L);
      FileSystemHandling.shouldAllThrowIOExceptions();
      try { 
        bufferedChannel0.flushAndForceWriteIfRegularFlush(true);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      FileChannel fileChannel0 = mockFileInputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 732);
      // Undeclared exception!
      try { 
        bufferedChannel0.flush();
        fail("Expecting exception: NonWritableChannelException");
      
      } catch(NonWritableChannelException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.EvoFileChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      fileChannel0.close();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1, 42L);
        fail("Expecting exception: ClosedChannelException");
      
      } catch(Throwable e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.EvoFileChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
      FileSystemHandling.shouldAllThrowIOExceptions();
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      FileChannel fileChannel0 = mockFileInputStream0.getChannel();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 732, 732);
        fail("Expecting exception: IOException");
      
      } catch(Throwable e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator(true);
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      FileChannel fileChannel0 = mockFileInputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 732, (-4561L));
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = PooledByteBufAllocator.DEFAULT;
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, (FileChannel) null, 2144553929, 2074485, 120L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.BufferedChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, (-2032), 89, 89);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // initialCapacity : -2032 (expected: >= 0)
         //
         verifyException("io.netty.util.internal.ObjectUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      FileSystemHandling.shouldAllThrowIOExceptions();
      FileChannel fileChannel0 = mockFileInputStream0.getChannel();
      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator(false);
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 0, 0, 0);
        fail("Expecting exception: IOException");
      
      } catch(Throwable e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = PooledByteBufAllocator.DEFAULT;
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      FileChannel fileChannel0 = mockFileInputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1746, 1044, 1746);
      assertEquals(0L, bufferedChannel0.position());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      fileChannel0.close();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1);
        fail("Expecting exception: ClosedChannelException");
      
      } catch(Throwable e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.EvoFileChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      FileChannel fileChannel0 = mockFileInputStream0.getChannel();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel((ByteBufAllocator) null, fileChannel0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.BufferedChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, (-2141757023));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // initialCapacity : -2141757023 (expected: >= 0)
         //
         verifyException("io.netty.util.internal.ObjectUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = PooledByteBufAllocator.DEFAULT;
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      FileSystemHandling.shouldAllThrowIOExceptions();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      FileChannel fileChannel0 = mockFileInputStream0.getChannel();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 732);
        fail("Expecting exception: IOException");
      
      } catch(Throwable e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      FileChannel fileChannel0 = mockFileInputStream0.getChannel();
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = new UnpooledByteBufAllocator(false);
      CompositeByteBuf compositeByteBuf0 = unpooledByteBufAllocator0.compositeHeapBuffer();
      BufferedChannel bufferedChannel0 = new BufferedChannel(unpooledByteBufAllocator0, fileChannel0, 3390);
      int int0 = bufferedChannel0.read((ByteBuf) compositeByteBuf0, (long) 3390);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1);
      bufferedChannel0.flush();
      UnpooledHeapByteBuf unpooledHeapByteBuf0 = new UnpooledHeapByteBuf(pooledByteBufAllocator0, 1, 1);
      long long0 = 42L;
      int int0 = 2145757374;
      BufferedChannel bufferedChannel1 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 2145757374, 1897L);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1);
      bufferedChannel0.flushAndForceWriteIfRegularFlush(false);
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1);
      bufferedChannel0.clear();
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1568);
      long long0 = bufferedChannel0.position();
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 18, 18);
      long long0 = bufferedChannel0.getUnpersistedBytes();
      assertEquals(0L, long0);
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 24, 604800L);
      bufferedChannel0.getNumOfBytesInWriteBuffer();
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      FileChannel fileChannel0 = mockFileInputStream0.getChannel();
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = new UnpooledByteBufAllocator(true);
      ByteBuf byteBuf0 = unpooledByteBufAllocator0.heapBuffer();
      BufferedChannel bufferedChannel0 = new BufferedChannel(unpooledByteBufAllocator0, fileChannel0, 1, (-697L));
      // Undeclared exception!
      try { 
        bufferedChannel0.read(byteBuf0, (-819L), 1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Negative position: -819
         //
         verifyException("org.evosuite.runtime.mock.java.io.EvoFileChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      FileChannel fileChannel0 = mockFileInputStream0.getChannel();
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = new UnpooledByteBufAllocator(true);
      ByteBuf byteBuf0 = unpooledByteBufAllocator0.heapBuffer();
      BufferedChannel bufferedChannel0 = new BufferedChannel(unpooledByteBufAllocator0, fileChannel0, 1, (-697L));
      bufferedChannel0.write(byteBuf0);
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
      assertEquals(0L, bufferedChannel0.position());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, false, 1);
      compositeByteBuf0.writeByte(1);
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1, 1);
      bufferedChannel0.write(compositeByteBuf0);
      assertEquals(1L, bufferedChannel0.position());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, false, 1);
      CompositeByteBuf compositeByteBuf1 = compositeByteBuf0.writeByte(1);
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 2838, 1);
      bufferedChannel0.write(compositeByteBuf0);
      try { 
        bufferedChannel0.read((ByteBuf) compositeByteBuf1, (long) 1, 1);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Read past EOF
         //
         verifyException("org.apache.bookkeeper.bookie.BufferedChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 24, 604800L);
      long long0 = bufferedChannel0.getFileChannelPosition();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = PooledByteBufAllocator.DEFAULT;
      assertEquals(0, pooledByteBufAllocator0.numThreadLocalCaches());
      
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      FileChannel fileChannel0 = mockFileInputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 4673);
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
  }
}
